<script>
    /**
     * As a note, this code is taken from sveltefire with modification to use the stores generated by FirestoreCacheStoreFactory.js
     * See the original source here: https://github.com/codediodeio/sveltefire/blob/32fce627fae5a442959f9bb27f0379c4bb51dc54/src/Collection.svelte
     */
    import {onDestroy, onMount, createEventDispatcher} from "svelte";

    export let store;
    const dispatch = createEventDispatcher();
    let unsub;
    // Props changed
    $: {
        if (unsub) {
            unsub();
            dispatch("ref", {ref: store.ref});
        }
        unsub = store.subscribe(data => {
            dispatch("data", {
                data
            });
        });
    }
    onMount(() => dispatch("ref", {ref: store.ref}))
    onDestroy(() => unsub());
</script>

<slot name="before"/>
{#if $store}
    {#if $store.loading}
        <slot name="loading"/>
    {:else}
        <slot data={$store}/>
    {/if}
{:else}
    <slot name="fallback"/>
{/if}
<slot name="after"/>